# Generated by Django 6.0.5 on 2026-05-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('asignatura', models.CharField(max_length=100)),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
        ),
    ]
